name: cv1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=23.3 
  - pip:
    - numpy==1.22.0
    - opencv-contrib-python==4.8.1.78 
    - matplotlib==3.3.4
    - jupyter==1.0.0
    - scikit-learn==1.3.1
    - scipy==1.11.3
    - scikit-image==0.22.0
    - torchvision==0.16
    - tensorflow<2.11
